concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}-run-build-with-tests
jobs:
  build-and-run-unit-test:
    name: Build & Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        architecture: x64
        cache: gradle
        distribution: zulu
        java-version: 11.0.22
    - continue-on-error: true
      name: Execute Gradle Build
      run: ./gradlew clean test --console=plain
    - continue-on-error: true
      if: always()
      name: Publish Test Report
      uses: mikepenz/action-junit-report@v3.5.0
      with:
        annotate_only: false
        check_name: Test Report
        fail_on_failure: true
        report_paths: '**/build/test-results/test/TEST-*.xml'
    - continue-on-error: true
      if: always()
      name: Delete previous comment of Github Actions Bot
      uses: izhangzhihao/delete-comment@master
      with:
        delete_user_name: github-actions[bot]
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issue_number: ${{ github.event.number }}
    - continue-on-error: true
      if: success()
      name: Notify current workflow is succeed
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "github.rest.issues.createComment({\n  issue_number: ${{ github.event.pull_request.number\
          \ }},\n  owner: 'naver',\n  repo: 'ngrinder',\n  body: '\u2705 Build & Test\
          \ workflow succeed \u2705\\n- [Show details](https://github.com/naver/ngrinder/actions/runs/${{\
          \ github.run_id }})'\n})\n"
    - continue-on-error: true
      if: failure()
      name: Notify current workflow is failed
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "github.rest.issues.createComment({\n  issue_number: ${{ github.event.pull_request.number\
          \ }},\n  owner: 'naver',\n  repo: 'ngrinder',\n  body: '\u274C Build & Test\
          \ workflow failed \u274C\\n- [Show details](https://github.com/naver/ngrinder/actions/runs/${{\
          \ github.run_id }})'\n})\n"
name: Run Build with Tests on PR
on:
  repository_dispatch:
    types: trigger-ga___run-build-with-test-on-pr.yml
